'use strict';

module.exports = {
    SUCCESS_CODE: 200,
    REQ_DATA_ERROR_CODE: 202,
    ERROR_CODE: 400,
    INVALID_CODE: 401,
    ALLREADY_EXIST: 201,
    INACTIVATE: 406,
    NOT_FOUND: 404,

    //IMAGE PATH
    PAGE_PATH: '/page',
    PRODUCT_PATH: '/product',
    PRODUCT_PATH_THUMB: '/product/thumb',
    CATEGORY_PATH: '/category',
    CATEGORY_PATH_THUMB: '/category/thumb',
    MURAL_PATH: '/murals',
    MURAL_PATH_SVG: '/murals/svg',
    MURAL_PATH_THUMB: '/murals/thumb',

    UNAUTHORISED: 'You are not authorised',
    //COMMON MESSAGE
    ADDED_SUCCESS: ' added successfully.',
    ADDED_UNSUCCESS: ' not added successfully.',
    UPDATED_SUCCESS: ' updated successfully.',
    UPDATED_UNSUCCESS: ' not updated successfully.',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    ALLREADY_REGISTERED: 'Already Registered.',
    FOUND_MESSAGE: 'Available.',
    NOT_FOUND_MESSAGE: ' Not found.',
    SUCCESS_GET_DATA: 'Successfully get data',
    NOT_FOUND_DATA: 'Data Not found.',
    VALID_TOKEN: 'Valid Token.',
    NOT_VALID_TOKEN: 'Not a Valid Token.',
    INTERNAL_ERROR: 'Request could not be processed. Please try again.',
    DATA_FETCH_SUCCESS: 'Data fetch successfully.',
    IMAGE_UPDALOAD_ERROR: 'Somthing went wrong while uploading Image.',
    //User Registration/login
    SIGNUP_SUCCESS: 'User Signup successfully. Please Verfiy the email',
    DEACTIVATED_SUCCESS: 'Your account has been deactivated successfully',
    DEACTIVATED_UNSUCCESS: 'Your account can not be deactivated now. Please try again',
    ACTIVATED_SUCCESS: 'Your account has been activated successfully',
    ACTIVATED_UNSUCCESS: 'Your account can not be activated now. Please try again',
    INVALID_EMAIL: 'Email is not valid.',
    REQUIRED_REGISTER_FIELDS: 'First name, Last name, Email and password is required.',
    PASSWORD_LENGTH_GREATER_THAN_FIVE: 'Password should be at least 6 characters.',
    EMAIL_ALREADY_EXIST: 'Email already exist.',
    LOGIN_REQUIRED_FIELDS: 'Email and password is required.',
    EMAIL_NOT_FOUND: 'Email Not found.',
    EMAIL_NOT_REGISTRED: 'Email Not register. Please register.',
    INVALID_LOGIN_DETAILS: 'Email/password is not correct.',
    VERIFY_ACCOUNT: 'Your Account is not active. Please activate Mural Monkey account by verifying through email.',
    INVALID_CURRENT_PASSWORD: 'Current password is invalid.',
    PASSWORD_CHANGED_SUCCESS: 'Password changed successfully.',
    PASSWORD_SENT_SUCCESS: 'Change Password request have been sent to your mail. Please verify it in one hour.',
    PASSWORD_SENT_UNSUCCESS: 'Could not process Change Password request. Please try again later.',
    PASSWORD_IS_INVALID: 'Invalid Password',
    NOT_PROPER_DATA: 'Request data is not proper',

    PRODUCT_SAVE_SUCCESS: 'Product saved successfully.',
    PRODUCT_PDF_SAVE_SUCCESS: 'Product PDF saved successfully.',
    PRODUCT_UPDATE_SUCCESS: 'Product Updated successfully.',
    PRODUCT_SAVE_UNSUCCESS: 'Product did not save.',
    PRODUCT_VARIATION_SAVE_SUCCESS: 'Product Variation Updated successfully.',
    PRODUCT_IMAGE_UPDATE_SUCCESS: 'Product Images Updated successfully.',
    PRODUCT_DELETED_SUCCESS: 'Product Deleted successfully.',
    PRODUCT_VIDEO_ADDED_SUCCESS: 'Product Video added successfully.',
    PRODUCT_FEEDBACK_SAVED_SUCCESS: 'Thank you for your feedback.',
    PRODUCT_FEEDBACK_SAVED_UNSUCCESS: 'Your feedback can not be proccessed now. Please try again later',
    PRODUCT_FEEDBACK_FOUND: 'Reviews found',
    PRODUCT_FEEDBACK_NOT_FOUND: 'Reviews not found',

    PAGE_SAVE_SUCCESS: 'Page saved successfully.',
    PAGE_UPDATE_SUCCESS: 'Page Updated successfully.',
    PAGE_SAVE_UNSUCCESS: 'Page did not save.',
    PAGE_DELETED_SUCCESS: 'Page Deleted successfully.',
    PAGE_URL_ALLRAEDY_USED: 'Page url already exists. please try another one.',
    PAGE_UPDATE_SUCCESS: 'Page Updated successfully.',
    PAGE_SAVE_UNSUCCESS: 'page did not save.',

    CART_SAVE_SUCCESS: 'Product saved to cart successfully.',
    CART_SAVE_UNSUCCESS: 'Product did not save to cart.',
    CART_UPDATE_SUCCESS: 'Cart Updated successfully.',
    CART_UPDATE_UNSUCCESS: 'Cart not Updated.',
    CART_DELETED_SUCCESS: 'Product Deleted from cart successfully.',

    EMAILTEMPLATE_SAVE_SUCCESS: 'Email Template saved successfully.',
    EMAILTEMPLATE_SAVE_UNSUCCESS: 'Email Template did not save.',
    EMAILTEMPLATE_DELETE_SUCCESS: 'Email Template Deleted Successfully',
    EMAILTEMPLATE_DELETE_UNSUCCESS: 'Email Template did not deleted',
    EMAILTEMPLATE_UPDATE_SUCCESS: 'Email Template Updated Successfully',
    PRODUCT_SAVE_UNSUCCESS: 'Product did not save.',
    // Brand
    BRAND_SAVE_SUCCESS: 'Brand saved successfully.',
    BRAND_SAVE_UNSUCCESS: 'Brand did not save.',
    BRAND_UPDATED_SUCCESS: 'Brand updated successfully.',
    BRAND_UPDATED_UNSUCCESS: 'Brand did not updated.',
    BRAND_DELETED_SUCCESS: 'Brand deleted successfully.',
    BRAND_DELETED_UNSUCCESS: 'Brand did not deleted.',
    // category
    CATEGORY_SAVE_SUCCESS: 'Category saved successfully.',
    CATEGORY_SAVE_UNSUCCESS: 'Category did not save.',
    CATEGORY_UPDATED_SUCCESS: 'Category updated successfully.',
    CATEGORY_UPDATED_UNSUCCESS: 'Category did not updated.',
    CATEGORY_DELETED_SUCCESS: 'Category deleted successfully.',
    CATEGORY_DELETED_UNSUCCESS: 'Category did not deleted.',
    CATEGORY_IMAGE_UPLOADED_SUCCESS: 'Category Image saved successfully.',
    CATEGORY_IMAGE_UPLOADED_UNSUCCESS: 'Category Image not saved.',


    ACCOUNT_INACTIVE: 'Your account is not activated yet. Please Verify your email.',
    ACCOUNT_ACTIVATED: 'Thank you for verifying. Please login to enjoy service',
    ACCOUNT_ALREADY_ACTIVATED: 'Your account is already activated.',
    SIGNIN_SUCCESS: 'User logged in successfully.',
    ACCOUNT_DEACTIVATED: 'Your account is not activated. Please check your email for confirmation or contact Uber Murals to activate your account.',
    ACCOUNT_DELETED: 'Your account is blocked. Please contact Uber Murals to activate your account.',
    PRODUCT_IMAGE_UPLOADED_SUCCESS: 'Product Image saved successfully.',
    PRODUCT_IMAGE_UPLOADED_UNSUCCESS: 'Product Image not saved.',

    // Faqs
    FAQ_ADDED_SUCCESS: 'Faq saved successfully.',
    FAQ_ADDED_UNSUCCESS: 'Faq did not save.',
    FAQ_UPDATED_SUCCESS: 'Faq detail updated successfully.',
    FAQ_UPDATED_UNSUCCESS: 'Faq detail did not updated.',
    FAQ_DELETED_SUCCESS: 'Faq detail deleted successfully.',
    FAQ_DELETED_UNSUCCESS: 'Faq detail did not deleted.',

    //Media
    MEDIA_ADDED_SUCCESS: 'Media saved successfully.',
    MEDIA_ADDED_UNSUCCESS: 'Media did not save.',
    MEDIA_UPDATED_SUCCESS: 'Media detail updated successfully.',
    MEDIA_UPDATED_UNSUCCESS: 'Media detail did not updated.',
    MEDIA_DELETED_SUCCESS: 'Media detail deleted successfully.',
    MEDIA_DELETED_UNSUCCESS: 'Media detail did not deleted.',

    // Recent Search
    RECENT_ADDED_SUCCESS: 'Recent saved successfully.',
    RECENT_ADDED_UNSUCCESS: 'Recent did not save.',

    // User Profilefile
    PROFILE_UPDATE_SUCCESS: 'Profile updated Successfully',
    PROFILE_UPDATE_SUCCESS_BUT_NOT_PROFILE_IMAGE: 'Profile updated Successfully, But we are unable to update your profile image',
    PROFILE_UPDATE_UNSUCCESS: 'Profile did not updated',

    //Favourite
    ADDED_AS_FAVOURITE_PRODUCT: 'Added as Favourite Product.',
    COULDNOT_ADDED_AS_FAVOURITE_PRODUCT: 'Sorry, Couldnt added as Favourite Product.',
    UNFAVOURITE_PRODUCT: 'Removed from Favourite Products',

    // Order
    ORDER_PLACED_SUCCESS: 'Order placed successfully',
    ORDER_PLACED_UNSUCCESS: 'Order did not placed',
    ORDER_DELETED_SUCCESS: 'Order deleted successfully',
    ORDER_DELETED_SUCCESS_WITHOUT_EMAIL: 'Order deleted successfully, but could not send email to user',
    ORDER_DELETED_UNSUCCESS: 'Order did not deleted',

    // Shipping
    SHIPPING_ADDRESS_ADDED_SUCCESS: 'Shipping address added successfully',
    SHIPPING_ADDRESS_ADDED_UNSUCCESS: 'Shipping address not added',
    SHIPPING_ADDRESS_UPDATED_SUCCESS: 'Shipping address updated successfully',
    SHIPPING_ADDRESS_UPDATED_UNSUCCESS: 'Shipping address not updated',
    SHIPPING_STATUS_UPDATED_SUCCESS: 'Shipping status updated successfully',
    SHIPPING_STATUS_UPDATED_SUCCESS_WITHOUT_EMAIL: 'Shipping status updated successfully, but could not send email to user',
    SHIPPING_STATUS_UPDATED_UNSUCCESS: 'Shipping status not updated',

    // Order Details
    ORDER_DETIALS_ADDED_SUCCESS: 'Order details added successfully',
    ORDER_DETIALS_ADDED_UNSUCCESS: 'Order details did not added',
    ORDER_DETIALS_UPDATED_UNSUCCESS: 'Order details did not updated',

    // Payment
    CARD_DETAIL_NOT_PROPER: 'Card detail is not proper',
    CARD_DECLINED: 'Card declined',
    CARD_TYPE_INVALID: 'Card type is invalid',
    CARD_INVALID_CVC: 'Invalid CVC',
    CARD_INVALID_CARD_NUMBER: 'Invalid card number',
    CARD_INVALID_EXPIRY_MONTH: 'Invalid expiry month',
    CARD_INVALID_EXPIRY_YEAR: 'Invalid expiry year',
    CARD_EXPIRED: 'Your Card is Expired',
    CARD_BAL_INSUFFICIENT: 'Insufficient amount to pay',
    PAYMENT_IS_SUCCESSFULL: 'Payment is successfull',
    PAYMENT_IS_NOT_SUCCESSFULL: 'There was a problem durng payment. Please try again',
    ORDER_DETIALS_ADDED_UNSUCCESS: 'Order details did not added',
};